# -*- coding: utf-8 -*-
"""SingleLL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Glt0ufrkwFS1NrZFArvRlgGl_GebUR3p
"""

#----------linked list--------#
class node:
  def __init__(self,val=None):
    self.val=val
    self.next=None

class Singlell:
  def __init__(self):
    self.head=None
    
  def begin(self,newdata):
    NewNode = node(newdata)

# Update the new nodes next val to existing node
        NewNode.next = self.head
        self.head = NewNode
   
  def listprint(self):
        printval = self.head
        while printval is not None:
            print (printval.val)
            printval = printval.next

class begin:
  def __init__(self):



l1=Singlell()
l1.head=node("mon")
# e2 = node("Tue")
# e3 = node("Wed")
# e4 = node("thur")
# Link first Node to second node
l1.head.next = node("Tue")
l1.head.next = node("wue")

# Link second Node to third node
# e2.next = e3
# e3.next= e4
l1.listprint()

##------adding node to begin---##