# -*- coding: utf-8 -*-
"""Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Glt0ufrkwFS1NrZFArvRlgGl_GebUR3p
"""

##----trees---#
class tree:
  def __init__(self,data):
    self.data=data
    self.parent=None
    self.children=[]
  
  def child(self,child):
    child.parent=self
    self.children.append(child)

  def printtree(self):
    print(self.data)
    #to print children
    for child in self.children:
      #prints only child of root.....i,e things->laptop
      #print(child.data)
      #to print appended children of laptop......use recursion
      child.printtree()




def build_tree():
  root=tree("things")
  laptop=tree("laptop")
  tv=tree("tv")
  tv.child(tree("samsung"))
  tv.child(tree("toshiba"))
  laptop.child(tree("macbook"))
  laptop.child(tree("dell"))

  root.child(laptop)
  root.child(tv)
  return root


if __name__=="__main__":
  root=build_tree()
  root.printtree()
  

#things
# laptop
# macbook
# dell
# tv
# samsung
# toshiba