# -*- coding: utf-8 -*-
"""BalancedParanthesis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Glt0ufrkwFS1NrZFArvRlgGl_GebUR3p
"""

#balanceed paranthesis
open_s =["[","(","{"]
close_s=["]",")","}"]
mystr="({[]})}]"
def cg(mystr):
  stack=[]
  for i in mystr:
    if i in open_s:
      stack.append(i)
    elif i in close_s:
      pos = close_s.index(i)
      if ((len(stack) > 0) and
                (open_s[pos] == stack[len(stack)-1])): 
                stack.pop()
      else: 
        return "Unbalanced"
  if len(stack) == 0:
    return "Balanced"
  else:
    return "Unbalanced"
print(cg(mystr))