# -*- coding: utf-8 -*-
"""CommonPrefix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Glt0ufrkwFS1NrZFArvRlgGl_GebUR3p
"""

#longest common prefix among strings in list
strs=["flow","flowp","flower"]
# strs="flower"
# print(strs[0:4])
def solution(strs):
  counter = 0
  for i in strs: 
      
    # incrementing counter 
    counter = counter + 1
  if (str(counter)==0):
    return(" ")
  if (str(counter)==1):  
    return(strs[0])
  pre=strs[0]
  p1leng=len(pre)
  for s in strs[1:]:
    while pre!=s[0:p1leng]:
      pre=pre[0:p1leng-1]
      p1leng -= 1
      if p1leng==0:
        return(" ")
  return pre
ese=solution(strs)
print(ese)